# ===== UWSM Check =====
exec-once = ~/.local/share/dotfiles/bin/check-uwsm

# ===== Core Services (not managed by systemd) =====
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# ===== Restore theme & wallpaper from last session =====
exec-once = ~/.local/share/dotfiles/bin/restore-session
