# ===== UWSM Check =====
exec-once = ~/.local/share/dotfiles/bin/check-uwsm

# ===== Core Services =====
exec-once = hyprpaper
exec-once = hypridle
exec-once = mako
exec-once = waybar
exec-once = swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# ===== Restore wallpaper from last session =====
exec-once = ~/.local/share/dotfiles/bin/restore-wallpaper
